name = "website"
type = "webpack"
account_id = "d3765f1c5f3d3ed76be2701b78510d29"
workers_dev = false
route = "bradyjoslin.com/*"
zone_id = "0b43369dd5bc0e0b2c3c768c1b478ee4"

[site]
bucket = "./public"
entry-point = "workers-site"
